[package]
name = "noto-linter"
description = "The official Noto linter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
noto-diagnostics.workspace = true
noto-ast.workspace = true
noto-semantic.workspace = true

[dev-dependencies]
noto-driver.workspace = true
