[package]
name = "noto-linter"
description = "The official Noto linter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
noto-span.workspace = true
noto-diagnostics.workspace = true
noto-ast.workspace = true
noto-parser.workspace = true
