[package]
name = "noto-test-runner"
description = "The official Noto test runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
noto-diagnostics.workspace = true
noto-span.workspace = true
noto-ir.workspace = true
noto-codegen.workspace = true
noto-runtime.workspace = true

[dev-dependencies]
noto-driver.workspace = true
