[package]
name = "noto-optimizer"
description = "Optimization passes over Noto IR"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
noto-ir.workspace = true
noto-span.workspace = true
