[package]
name = "noto-diagnostics"
description = "Diagnostic reporting and rendering for the Noto compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
noto-span.workspace = true
